import '../styles/index.scss';
// import './chapter5-composition/composition-samples';
// import './chapter6-exampleapp/example-app';
// import './chapter8-functors/functor-samples';
// import './chapter8-functors/async-task-samples';
// import './chapter8-functors/chapter8-exercises';
// import './chapter9-monads/monad-samples';
// import './chapter9-monads/chapter9-exercises';
//  import './chapter10-apfunctors/apfunc-samples';
import './chapter10-apfunctors/apfunc-exercises';